#:schema node_modules/wrangler/config-schema.json
name = "pokerly"
main = ".open-next/worker.js"
compatibility_date = "2024-09-23"
compatibility_flags = ["nodejs_compat"]

# Assets (static files)
assets = { directory = ".open-next/assets", binding = "ASSETS" }
